version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      HISTFILE: .mysql_history
    ports:
      - "3306:3306"
    volumes:
      # - .my.cnf:/etc/mysql/my.cnf
      - mysql_data:/var/lib/mysql
      - ~/.mysql_history:/root/.mysql_history

  api:
    build: ./api
    ports:
      - "8000:8000"

  # api:
  #   image: tiangolo/uvicorn-gunicorn-fastapi:python3.10
  #   platform: linux/arm64/v8
  #   ports:
  #     - "8000:8000"

  phpmyadmin:
    image: arm64v8/phpmyadmin
    platform: linux/arm64
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  mysql_data: {}
