version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      HISTFILE: .mysql_history
    ports:
      - "3306:3306"
    volumes:
      - .my.cnf:/etc/mysql/my.cnf
      - ~/.mysql_history:/root/.mysql_history
